# Generated by Django 5.1.5 on 2025-02-20 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Награды', 'verbose_name_plural': 'награды'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Библиотека', 'verbose_name_plural': 'библиотеки'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/def_avatar.png', null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
