# Generated by Django 5.1.5 on 2025-02-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_award_options_alter_library_options_and_more'),
        ('catalog', '0003_remove_book_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.book', verbose_name='Книга'),
        ),
    ]
