# Generated by Django 5.1.5 on 2025-03-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_comment_book'),
        ('catalog', '0003_remove_book_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='desired_by', to='catalog.book', verbose_name='Желаемое'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=2056, verbose_name='Комментарий'),
        ),
    ]
