# Generated by Django 5.1.5 on 2025-01-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.CharField(choices=[('PB', 'Бумажная'), ('EB', 'Электронная'), ('AB', 'Аудиокнига')], max_length=2, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
