# Generated by Django 5.1.5 on 2025-02-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
    ]
