# Generated by Django 5.1.5 on 2025-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='books/covers/default_cover.png', null=True, upload_to='books/covers/', verbose_name='Обложка книги'),
        ),
    ]
