# Generated by Django 5.1.5 on 2025-04-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='def_slug', max_length=64, verbose_name='Слаг'),
        ),
    ]
